Adding TerrarianEditor
mertwole/miniature-happiness pull request #1
Opened 2023-04-09 09:17 UTC by Kiuh

Добавлена сцена в которой можно создать окружение для локации.
Добавлен управляющий скрипт для тайлов.
Добавлен скрипт тайлов, инкапсулирующий передвижение и поворот находящимся в них элементов.
Правила составления тайлов вписаны в сам тайл.

2023-04-09 12:19 UTC, mertwole requested changes

2023-04-09 12:19 UTC, mertwole commented on JamGame/Assets/Scripts/Terrarian/TerrarianBuilder.cs
> +        if (EditorMode)
Логику ввода лучше переместить в отдельный скрипт, оставив здесь только api для изменения поля

2023-04-09 12:19 UTC, mertwole commented on JamGame/Assets/Scripts/Terrarian/TerrarianBuilder.cs
> +}
При добавлении клетки можно обновлять не все поле, а только соседние клетки

2023-04-09 12:19 UTC, mertwole commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +}
В эти структуры можно добавить методя для включения/выключения стен и углов

2023-04-09 12:19 UTC, mertwole commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +    [SerializeField] List<TTCenterMap> center_objects = new();
здесь можно хранить два TerrainTileInfo : исходный и повернутый

2023-04-09 12:19 UTC, mertwole commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +    public void Move(Direction direction)
обновление стен?

2023-04-09 12:19 UTC, mertwole commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +    public void Rotate(int ticks)
Здесь надо кешировать повернутый стейт

2023-04-09 12:19 UTC, mertwole commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +    TerrarianTileWallObject ChooseWall(List<TerrarianTileMark> TTmark_1, List<TerrarianTileWallObject> TTavailable_walls_1, List<TerrarianTileMark> TTmark_2, List<TerrarianTileWallObject> TTavailable
На основе правил

2023-04-09 12:19 UTC, mertwole commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +    TerrarianTileCornerObject ChooseCorner(List<TerrarianTileMark> TTmark_1, List<TerrarianTileMark> TTmark_2, List<TerrarianTileMark> TTmark_3, List<TerrarianTileMark> TTmark_4)
на основе правил

2023-04-09 12:19 UTC, mertwole commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +public enum TerrarianTileMark
лучше хранить тэги в строках

2023-04-09 12:19 UTC, mertwole commented on JamGame/Assets/Scripts/Terrarian/TerrarianBuilder.cs
> +public class TerrarianBuilder : MonoBehaviour
сюда можно инкапсулировать обьект IActionValidator, который будет разрешать/запрещать движение или поворот комнат

2023-04-10 19:46 UTC, merged

2023-04-10 19:46 UTC, Kiuh commented on JamGame/Assets/Scripts/Terrarian/TerrarianBuilder.cs
> +        if (EditorMode)
Исправлено

2023-04-10 19:47 UTC, Kiuh commented on JamGame/Assets/Scripts/Terrarian/TerrarianBuilder.cs
> +}
Исправлено

2023-04-10 19:47 UTC, Kiuh commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +}
Не понадобилось

2023-04-10 19:47 UTC, Kiuh commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +    [SerializeField] List<TTCenterMap> center_objects = new();
Сделано по другому, в виде кеша на повернутые стены

2023-04-10 19:48 UTC, Kiuh commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +    public void Move(Direction direction)
Обновление стен?

2023-04-10 19:48 UTC, Kiuh commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +    public void Rotate(int ticks)
Ну, типа сделано

2023-04-10 19:49 UTC, Kiuh commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +    TerrarianTileWallObject ChooseWall(List<TerrarianTileMark> TTmark_1, List<TerrarianTileWallObject> TTavailable_walls_1, List<TerrarianTileMark> TTmark_2, List<TerrarianTileWallObject> TTavailable
Сделано сомнительно

2023-04-10 19:49 UTC, Kiuh commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +    TerrarianTileCornerObject ChooseCorner(List<TerrarianTileMark> TTmark_1, List<TerrarianTileMark> TTmark_2, List<TerrarianTileMark> TTmark_3, List<TerrarianTileMark> TTmark_4)
Нет

2023-04-10 19:49 UTC, Kiuh commented on JamGame/Assets/Scripts/Terrarian/TerrarianTile.cs
> +public enum TerrarianTileMark
Расскажи ещё

2023-04-10 19:50 UTC, Kiuh commented on JamGame/Assets/Scripts/Terrarian/TerrarianBuilder.cs
> +public class TerrarianBuilder : MonoBehaviour
В следующей жизни (при следующем реквесте)