Tile Editor Completing
mertwole/miniature-happiness pull request #2
Opened 2023-04-11 11:15 UTC by Kiuh

Исправлена структура
Добавлена система автозаполнения префабами тайла
Добавлено сохранение состояния сцены

2023-04-11 13:55 UTC, mertwole requested changes

2023-04-11 13:55 UTC, mertwole commented on JamGame/Assets/Scripts/StaticScripts/Bezier.cs
Перенеси в Common

2023-04-11 13:55 UTC, mertwole commented on JamGame/Assets/Scripts/Tile/Tile.cs
> +public class WallPrefabCollection
Не исправил. Инкапсулируй сюда SetWall(), аналогично с углами

2023-04-11 13:55 UTC, mertwole commented on JamGame/Assets/Scripts/Tile/Tile.cs
> +    [SerializeField] private List<TileWallType> wallsPriorityQueue = new() {
точно нужно так много public?

2023-04-11 13:55 UTC, mertwole commented on JamGame/Assets/Scripts/Tile/TileEnums.cs
> +public enum TileType
тебе не надо это, только набор тэгов

2023-04-11 13:55 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileBuilder.cs
> +        Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
В классе TileBuilder не должно быть логики ввода

2023-04-11 13:55 UTC, mertwole commented on JamGame/Assets/Scripts/BuilderControllers/TileBuilderControllerEditor.cs
Название файла и класса не соответствует содержанию

2023-04-11 13:55 UTC, mertwole commented on JamGame/Assets/Scripts/Tile/TileEnums.cs
> +public enum TileMark
Это должны быть строки

2023-04-11 13:56 UTC, mertwole commented on JamGame/Assets/Scripts/Tile/Tile.cs
> +    [SerializeField] private List<TileWallType> wallsPriorityQueue = new() {
(Коммент к строчке ниже)

2023-04-11 14:59 UTC, Kiuh commented on JamGame/Assets/Scripts/BuilderControllers/TileBuilderControllerEditor.cs
Это файл содержащий модификацию для TileBuilderController для работы с ним в Эдиторе

2023-04-11 17:09 UTC, mertwole commented on JamGame/Assets/Scripts/BuilderControllers/TileBuilderControllerEditor.cs
Назови его так, чтобы было понятно что он сцену сохраняет и загружает

2023-04-11 17:44 UTC, Kiuh commented on JamGame/Assets/Scripts/BuilderControllers/TileBuilderControllerEditor.cs
Ну, теперь он не только это делает, так что все норм

2023-04-11 17:46 UTC, Kiuh commented on JamGame/Assets/Scripts/Tile/TileEnums.cs
> +public enum TileType
По каким критериям будут определятся уникальные тайлы без этого параметра?

2023-04-12 17:03 UTC, mertwole commented on JamGame/Assets/Scripts/BuilderValidator/BuilderValidator.cs
> +    bool GameMode = false;
Сделай валидатора интерфейсом, который реализуют два класса, чтобы в каждом методе не было ifов. И чтобы не тащить все методы из билдера, лучше все-таки реализуй их в виде обьектов IBuilderCommand

2023-04-12 17:05 UTC, mertwole commented on JamGame/Assets/Scripts/BuilderValidator/BuilderValidator.cs
> +    [SerializeField] GameObject outdoorPrefab;
Это же только для отладки и в финальной версии этого не будет?

2023-04-12 17:09 UTC, mertwole commented on JamGame/Assets/Scripts/BuilderController/TileBuilderController.cs
> +    [SerializeField] BuilderValidator builderValidator;
Сделай лучше чтобы валидатор был внутри билдера, чтобы гарантированно нельзя было рбращатся к билдеру напрямую

2023-04-12 17:13 UTC, mertwole commented on JamGame/Assets/Scripts/Tile/Tile.cs
> +                    Debug.LogWarning($"Cannot find prefab for {handler.Type}");
Это должна быть ошибка или вообще исключение, потому что ворнинг можно и пропустить

2023-04-15 19:23 UTC, mertwole requested changes

2023-04-15 19:23 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +    public Dictionary<TileWallPlace, List<TileWallType>> Walls { get { return cached_walls; } }
Почему в самом низу?

2023-04-15 19:23 UTC, mertwole commented on JamGame/Assets/Scripts/EditorScripts/LocationSaveLoaderEditor.cs
Убери тогда Editor из названий фалов и классов в этой папке

2023-04-15 19:23 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Validators/GameingValidator.cs
GameModeValidator

2023-04-15 19:23 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Validators/BuildingValidator.cs
BuildModeValidator

2023-04-15 20:58 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +    public Dictionary<TileWallPlace, List<TileWallType>> Walls { get { return cached_walls; } }
А где тогда?
Я привык геттеры и сеттеры всегда в самом конце определять

2023-04-15 21:01 UTC, Kiuh commented on JamGame/Assets/Scripts/EditorScripts/LocationSaveLoaderEditor.cs
Тогда они будут конфликтовать с названиями классов

2023-04-15 21:06 UTC, Kiuh commented on JamGame/Assets/Scripts/EditorScripts/LocationSaveLoaderEditor.cs
+ Нельзя писать несколько скриптов для одного эдитора, потому будет так.

2023-04-16 08:36 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +    public Dictionary<TileWallPlace, List<TileWallType>> Walls { get { return cached_walls; } }
вверху

2023-04-16 08:37 UTC, mertwole commented on JamGame/Assets/Scripts/EditorScripts/LocationSaveLoaderEditor.cs
а namespace?

2023-04-16 08:38 UTC, mertwole commented on JamGame/Assets/Scripts/EditorScripts/LocationSaveLoaderEditor.cs
несколько скриптов - partial классы

2023-04-16 12:43 UTC, mertwole approved these changes

2023-04-16 12:45 UTC, merged