Tile editor
mertwole/miniature-happiness pull request #3
Opened 2023-04-28 19:18 UTC by Kiuh

Adding Base Functions to Editor

2023-04-29 09:39 UTC, mertwole requested changes

2023-04-29 09:39 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
UpdateWalls() Точно нужна еще?

2023-04-29 09:39 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
> +    Vector2 GetRightPoint(Vector2 vector)
Название странное, логику можно проще написать

2023-04-29 09:39 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Validators/BuildModeValidator.cs
> +            if (selectedTileUnion.IsAllWithMark("freecpace"))
freespace

2023-04-29 09:39 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Validators/BuildModeValidator.cs
> +            if (selectedTileUnion.IsAllWithMark("freecpace"))
И везде так же

2023-04-29 09:39 UTC, mertwole commented on JamGame/Assets/Scripts/NewBehaviourScript.cs
???

2023-04-29 11:37 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/Tile/WallSolver.cs
ScriptableObject? или ты хочешь каждому тайлу отдельный солвер создать?

2023-04-29 12:03 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileBuilder/BuilderMatrix.cs
> +    }
![image](https://user-images.githubusercontent.com/30412223/235301503-da3a7c7e-3c90-4893-90bd-7d9f95bfa3d6.png)
Мне нужен именно эффект Trncate

2023-04-29 12:05 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileBuilder/BuilderMatrix.cs
> +    }
Тоже не совсем подходит

2023-04-29 12:08 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
> +    public List<Tile> IsValidPlacing(Dictionary<Vector2Int, Tile> tilePairs)
Не обновляя стены, все так как сказал

2023-04-29 12:12 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
> +    Vector2 GetRightPoint(Vector2 vector)
Не вижу возможности как написать проще

2023-04-29 12:27 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
> +    public List<Vector2Int> TilesPositionsForUpdating
Зачем? Вдругих местах просто появится ToList()

2023-04-29 12:27 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileBuilder/TileBuilder.cs
> +    void UpdateWallsInTileUnion(TileUnion tileUnion)
Нет, ему тогда надо будет давать все тайлы

2023-04-29 12:28 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileBuilder/TileBuilder.cs
> +    void UpdateCornersInTileUnion(TileUnion tileUnion)
Аналогично

2023-04-29 12:30 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
Точно

2023-05-01 21:23 UTC, mertwole requested changes

2023-05-01 21:23 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Tile/WallSolver.cs
>      };
тогда уже можно задать значения в инспекторе и запихнуть WallSolver в префаб

2023-05-01 21:23 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileBuilder/TileBuilder.cs
> +        // All good
That's fine. But do we really need this comment?

2023-05-01 21:23 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
> +    IEnumerable<Vector2Int> GetNinePositions()
NeighborPositions получше звучит

2023-05-01 21:23 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
>      public Vector2Int Position
строчка с Rotation не комментируется, поэтому здесь.
1. Свойства лучше использовыать для простой логики валидации, а когда логика становится сложнее, то очень неявно выглядит когда она в свойстве
2. Вместо while в Rotation можно юзать арифметические операции (с отрицательными числами в % аккуратнее)
3. В Position тоже добавится логика валидации наверно, так что для него то же самое, что и для Rotation
4. Сокращенная форма записи для get/set (В других местах кода тоже)

2023-05-03 21:54 UTC, mertwole requested changes

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +    public void Awake()
а public-то зачем?)

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Common/Result.cs
> +    }
Лучше не надо во внешний код это показывать, более типобезопасно будет если Result с разными T были разными типами и нигде не приводились к родительскому

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +    public Result RequestWallUpdates(Dictionary<Direction, Tile> neighbours)
1. Не типобезопасно
2. Сигнатура метода не говорит о том, что он возвращает. Из нее понятно, что возвращается **какой-то** Result

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +        return new SuccessResult<Dictionary<Direction, TileWallType>>(configuration);
Лучше обернуть все-таки этот тип в структуру/класс, а то уже смутно понятно, что он значит

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +    }
а зачем? у тебя есть прекрасный метод для этого чуть ниже

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +        Errored,
не, не нужен тут невалидный вариант

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +    }
вот это уже работает с материалами, явно не бизнес-логика

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +        this.rotation = rotation % 4;
с отрицательными не работает так, как ты думаешь. самое простое - не int сюда передавать, а что-то беззнаковое

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileBuilder/BuilderMatrix.cs
> +public class BuilderMatrix: ScriptableObject
а зачем ему SO быть? будет место в проводнике редактора занимать, а используеется только в билдере

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileBuilder/BuilderMatrix.cs
> +    public Result GetMatrixPosition(Ray ray)
Не критично, можешь не менять, но Result тут не очень логично смотрится. FailResult это что-то ошибочное, здесь же когда луч не попадает в сетку это щтатная ситуация (для такого юзают Option тип)

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileBuilder/WallSolver.cs
> +public class WallSolver : ScriptableObject
Ему тоже не надо быть SO, он только в билдере лежит

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
> +    [SerializeField] BuilderMatrix builderMatrix;
зачем ему быть SerializeField?

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnionInspector/TileUnionPlacer.cs
> +            tileUnion.CreateTileUnionCehe();
cache

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnionTools.cs
> +    }
а чем оно тебе в TileUnion мешало?

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Common/Direction.cs
> +                dir = dir.Rotate90();
вот так лучше не делать, как минимум потому что если кто-то не дойдет до конца итератора, то dir очень внезапно поменяется

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/Validators/BuildModeValidator.cs
> +                pickedPosition = Vector2Int.zero;
странное поведение, может просто режектить такое?

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
> +    void SetTileUnionPosition(Vector2Int vector)
Просто SetPosition, из контекста понятно, что у TileUnion

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
> +        this.rotation = rotation % 4;
То же самое, что и в Tile

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
> +    public void UpdateCornersInTile(TileBuilder tileBuilder, Vector2Int position)
то же самое

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
> +    public void UpdateWallsInTile(TileBuilder tileBuilder, Vector2Int position)
не надо решать за тайл, что ему делать

2023-05-03 21:54 UTC, mertwole commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnion.cs
> +    public int Rotation { get => rotation; set => SetTileUnionRotationFromCehe(value); }
тут тоже сеттеры слишком сильно стейт меняют

2023-05-04 18:48 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileUnion/TileUnionTools.cs
> +    }
Валидатор использовал этот метод, с целью, не относящейся к экземпляру используемого тайла.

2023-05-05 15:38 UTC, mertwole approved these changes

2023-05-05 15:40 UTC, merged