Level sheduer
mertwole/miniature-happiness pull request #5
Opened 2023-05-18 21:40 UTC by Kiuh

Level Sheduer
Main structure
Shop UI
Finances UI
Boss stress UI
Little refactor of scripts interact
Level config

2023-05-20 11:29 UTC, mertwole requested changes

2023-05-20 11:29 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/TileBuilderController/TileBuilderController.cs
> +    public Action СompleteMeetingEvent;
Why builder knows about meetings?

2023-05-20 11:29 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/ConfigFiles/LevelConfig.cs
> +}
Make all the fields readonly (`List<DayConfig>` too, see https://github.com/mertwole/miniature-happiness/blob/f7d204c6068b0e6f7c4d101bb9c684a375c3a5e4/JamGame/Assets/Scripts/Employee/Buff/Effect/NeedModifierEffect.cs#L10)

2023-05-20 11:29 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/ConfigFiles/RoomConfigs/AbstractRoomConfig.cs
> +}
Make this an `interface`

2023-05-20 11:29 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/ConfigFiles/RoomConfigs/RoomConfig.cs
> +    public RoomShopUI RoomShopUI;
make this readonly from the outer code

2023-05-20 11:29 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/ConfigFiles/EmployeeConfigs/AbstractEmployeeConfig.cs
> +}
make this an `interface`

2023-05-20 11:29 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/ConfigFiles/EmployeeConfigs/EmployeeConfig.cs
> +    }
Make all the fields readonly

2023-05-20 11:29 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/ConfigFiles/EmployeeConfigs/RandomEmployeeConfig.cs
> +    private static readonly string[] lastNames = { "Lennon", "McCartney", "Starr", "Harrison" };
Better reference here to the other SO containing all the possible names

2023-05-20 11:29 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/FinancesController.cs
> +    [SerializeField] private FinancesCounter financesCounter;
Why the Controller references View?

2023-05-20 11:29 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/FinancesController.cs
Is it really a controller?

2023-05-20 11:29 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/LevelExecutor.cs
> +    public ShopController ShopController;
do we really need all the fields public?

2023-05-21 21:04 UTC, Kiuh commented on JamGame/Assets/Scripts/LevelManagement/TileBuilderController/TileBuilderController.cs
> +    public TileBuilder TileBuilder;
Потому что в команде MoveSelectedTileToRayCommand, нужен доступ к контроллеру, чтобы преобразовать команду в другую. Ранее я передавал в команды Builder, и он мог выполнять команды, сейчас - по-другому, а конандам в любом случае нужен Builder, и он находиться в контроллере.

2023-05-21 21:38 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/Commands/MoveSelectedTileToRayCommand.cs
> +                    ? Direction.Right : Direction.Left : delta.y > 0 ? Direction.Up : Direction.Down;
Rewrited

2023-05-21 22:00 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +                                                    : wallsBools.Wall4 == true && wallsBools.Wall3 == true ? TileCornerType.OutsideLeft : TileCornerType.None;
Rewrited

2023-05-21 22:03 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/Tile/Tile.cs
> +    public Dictionary<Direction, List<TileWallType>> WallsDictionary
Rewrited

2023-05-21 22:11 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileBuilder/BuilderMatrix.cs
> +    [SerializeField] private float selectingPlaneHeight = 1;
Yes

2023-05-22 08:28 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileBuilder/BuilderMatrix.cs
> +    public int Step = 5;
Не можно, так как исаользуется в разых местах, сделал геттером

2023-05-22 08:29 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileBuilder/TileBuilder.cs
> +    public string SavingName = "SampleBuilding";
Discussed

2023-05-22 08:42 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileBuilder/WallSolver.cs
> +        TileWallType.None
Fixed

2023-05-26 05:06 UTC, mertwole requested changes

2023-05-26 05:06 UTC, mertwole commented on JamGame/Assets/Scripts/UI/BuilderUI/RoomInventoryUI.cs
> +    public class InitAnsver
If it's InitAns**W**er better call it InitResult

2023-05-26 05:06 UTC, mertwole commented on JamGame/Assets/Scripts/UI/BuilderUI/RoomInventoryUI.cs
> +    public class InitAnsver
Is it duplicates Result?

2023-05-26 05:06 UTC, mertwole commented on JamGame/Assets/Scripts/UI/DailyBillPanel/DailyBillPanel.cs
> +    public void ShowDailyBill(Check check)
Model calls UI...

2023-05-26 10:13 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/TileBuilder/TileBuilder.cs
>  public class TileBuilder : MonoBehaviour
You made me feel pain. I didn`t want to do this now.

2023-05-26 12:02 UTC, Kiuh commented on JamGame/Assets/Scripts/Builder/Tile/TileView.cs
> +        SetActiveChilds(transform);
Because you cannot get component in disable gameObject

2023-05-29 21:59 UTC, mertwole requested changes

2023-05-29 21:59 UTC, mertwole commented on JamGame/Assets/Scripts/Common/InspectorReadOnlyAttribute.cs
Don't split this into 2 files

2023-05-29 21:59 UTC, mertwole commented on JamGame/Assets/Scripts/Common/NotifyCollectionChangedAction.cs
Can we just use built-in `NotifyCollectionChangedAction` instead of this?

2023-05-29 21:59 UTC, mertwole commented on JamGame/Assets/Scripts/Common/RotationDirection.cs
> +        Left = -1
```suggestion
        Clockwise = 1,
        CounterClockwise = -1
```

2023-05-29 21:59 UTC, mertwole commented on JamGame/Assets/Scripts/Common/RotationDirection.cs
> +        }
`(int)direction` would be shorter in this case:)

2023-05-29 21:59 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/UIController/UIControllerEditor.cs
> +                    string text = $"Animator {index} name: ";
Can we just display name instead of index?

2023-05-29 21:59 UTC, mertwole commented on JamGame/Assets/Scripts/LevelManagement/LevelExecutor/LevelExecutor.cs
> +public partial class LevelExecutor : MonoBehaviour
Just implement event here that will be invoked when the action ends

2023-05-31 11:29 UTC, merged